In [1]:
import numpy as np

In [2]:
np.array ([20,30,40])


array([20, 30, 40])

In [3]:
array1 = np.array ([10,12,14,16,20])
print (array1)


[10 12 14 16 20]


In [4]:
np.array ([])

array([], dtype=float64)

In [5]:
np.array ([[20,30,40],[35,45,38]])

array([[20, 30, 40],
       [35, 45, 38]])

In [6]:
list1 = [[10,20,30],[50,60,70]]
print (list1)


[[10, 20, 30], [50, 60, 70]]


In [7]:
np.array (list1)

array([[10, 20, 30],
       [50, 60, 70]])

In [8]:
list1 = [[10,20.8,True],[50,60,70]]
print (list1)

[[10, 20.8, True], [50, 60, 70]]


In [9]:
np.array (list1)

array([[10. , 20.8,  1. ],
       [50. , 60. , 70. ]])

In [10]:
np.array ([[20,30,40],[35,45,38]])

array([[20, 30, 40],
       [35, 45, 38]])

In [11]:
np.array ([[20,30,40],[35,38]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [12]:
np.array ([[20,30,40],[35,0,38]])

array([[20, 30, 40],
       [35,  0, 38]])

In [13]:
np.array ([[20,30,40],[35,np.nan,38]])

array([[20., 30., 40.],
       [35., nan, 38.]])

In [14]:
Tup1 = (10,20,30,40,50,'x','y')
Tup1

(10, 20, 30, 40, 50, 'x', 'y')

In [15]:
array1 = np.array (Tup1)
array1

array(['10', '20', '30', '40', '50', 'x', 'y'], dtype='<U11')

In [23]:
a = np.array ([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [24]:
b = a[2:5]
b

array([30, 40, 50])

In [27]:
b[1]=4
b

array([30,  4, 50])

In [28]:
a

array([10, 20, 30,  4, 50, 60, 70, 80])

In [29]:
a = np.array ([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [30]:
b = a[2:5].copy()
b

array([30, 40, 50])

In [31]:
b[1]=44444
b

array([   30, 44444,    50])

In [32]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [33]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
a = np.arange(10,20,2)
a

array([10, 12, 14, 16, 18])

In [37]:
a = np.arange(10,12,.2)
a

array([10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8])

In [38]:
a = np.arange(100,-100,-10)
a

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10,   0, -10, -20,
       -30, -40, -50, -60, -70, -80, -90])

In [39]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
a.reshape (3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
a.reshape (4,2)

ValueError: cannot reshape array of size 9 into shape (4,2)

In [42]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
a.reshape (6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [44]:
a.reshape (5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [45]:
a.reshape (3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [46]:
a.reshape (2,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [47]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
b = np.ones((5,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
b*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])